"use client";

import Head from "next/head";
import ContactSection from "~/components/blocs/landing/ContactSection";
import FAQSection from "~/components/blocs/landing/Faq";
import Hero from "~/components/blocs/landing/Hero";
import ProductListSection from "~/components/blocs/landing/ProductListSection";
import ServicesSection from "~/components/blocs/landing/ServicesSection";
import Navbar from "~/components/blocs/landing/navbar";
import Footer from "~/components/blocs/landing/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Essenya</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Navbar />
        <Hero />
        <main className="pt-20">
          <ProductListSection />
          <FAQSection />
          <ServicesSection />
          <ContactSection />
          <Footer />
        </main>
      </>
    </>
  );
}
