"use client";

import Head from "next/head";
import FAQ from "~/components/blocs/landing/Faq";
import Features from "~/components/blocs/landing/Features";
import Footer from "~/components/blocs/landing/Footer";
import Hero from "~/components/blocs/landing/Hero";
import Pricing from "~/components/blocs/landing/Pricing";
import Testimonials from "~/components/blocs/landing/Testimonials";
import Navbar from "~/components/blocs/landing/navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Essenya</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Navbar />
        <Hero />
        <main className="space-y-24 pt-20">
          <Features />
          <Pricing />
          <Testimonials />
          <FAQ />
          <Footer />
        </main>
      </>
    </>
  );
}
