import React, { useState } from "react";
import Carousel from "~/components/blocs/dashboard/Carousel";
import { ProductList } from "~/components/blocs/dashboard/ProductList";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import Statistics from "~/components/blocs/dashboard/Statistics";
import ProductFilterBar from "~/components/blocs/dashboard/filter/ProductFilterSection";
import { Calendar } from "lucide-react";
import { PaginationContextProvider } from "~/common/components/pagination/context/pagination.context";
import Head from "next/head";
import Navbar from "~/components/blocs/landing/navbar";
import Footer from "~/components/blocs/landing/Footer";

const Product = () => {
  const [searchTerm, setSearchTerm] = useState<string>("");
  const [tags, setTags] = useState<string[]>([]);
  const [priceRange, setPriceRange] = useState<[number, number]>([0, 100]);

  // Active filters state - only update when "Apply Filters" is clicked
  const [activeFilters, setActiveFilters] = useState<{
    tags: string[];
    priceMin: number;
    priceMax: number;
  }>({
    tags: [],
    priceMin: 0,
    priceMax: 100,
  });

  const handleApplyFilters = (filters: unknown) => {
    const typedFilters = filters as {
      tags: string[];
      priceMin: number;
      priceMax: number;
    };
    setActiveFilters(typedFilters);
    console.log("Applied filters:", typedFilters);
  };

  return (
    <>
      <Head>
        <title>Essenya</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Navbar />
        <main className="flex justify-center bg-[#f0fbf8] pt-20 dark:bg-[#18202f]">
          <div className="min-h-screen max-w-7xl">
            <div className="space-y-6 p-6">
              {/* Statistics Cards Section */}
              <div className="space-y-4">
                <Statistics />
              </div>

              {/* Upcoming Events Carousel Card */}
              <Card className="gap-0">
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <CardTitle className="flex items-center">
                      <div className="flex space-x-2">
                        <Calendar className="text-primary" />
                        <h1 className="text-xl font-semibold">
                          Événements à venir
                        </h1>
                      </div>
                    </CardTitle>
                  </div>
                </CardHeader>
                <CardContent className="p-0">
                  <Carousel />
                </CardContent>
              </Card>

              {/* Products Marketplace Card */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-xl font-semibold">
                    Marché des Produits Frais
                  </CardTitle>
                  <div className="flex flex-col space-y-4 sm:flex-row sm:items-center sm:justify-between sm:space-y-0">
                    <div>
                      <p className="text-muted-foreground text-sm">
                        Affichage des produits
                      </p>
                    </div>
                    <div className="flex items-center gap-4">
                      <div className="flex gap-2">
                        {/* Horizontal Filter Bar */}
                        <ProductFilterBar
                          onFilter={handleApplyFilters}
                          setSearchTerm={setSearchTerm}
                          tags={tags}
                          setTags={setTags}
                          priceRange={priceRange}
                          setPriceRange={setPriceRange}
                        />
                        <Select defaultValue="relevance">
                          <SelectTrigger className="focus:ring-primary bg-background rounded-md border border-gray-300 px-3 py-2 focus:ring-2 focus:outline-none">
                            <SelectValue placeholder="Sort by" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="relevance">
                              Sort by relevance
                            </SelectItem>
                            <SelectItem value="price_low_high">
                              Price: Low to High
                            </SelectItem>
                            <SelectItem value="price_high_low">
                              Price: High to Low
                            </SelectItem>
                            <SelectItem value="newest">Newest First</SelectItem>
                            <SelectItem value="rating">
                              Highest Rated
                            </SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="space-y-6">
                  {/* Products Grid */}
                  <PaginationContextProvider ressourcesName="Type">
                    <ProductList
                      searchValue={searchTerm}
                      tags={activeFilters.tags}
                      priceMin={activeFilters.priceMin}
                      priceMax={activeFilters.priceMax}
                    />
                  </PaginationContextProvider>
                </CardContent>
              </Card>
            </div>
          </div>
        </main>
        <Footer />
      </>
    </>
  );
};

export default Product;
