"use client";

import Head from "next/head";
import Navbar from "~/components/blocs/landing/navbar";
import Footer from "~/components/blocs/landing/Footer";
import PublicEventsCalendar from "~/components/blocs/event-management/PublicEventsCalendar";
export default function Events() {
  return (
    <>
      <Head>
        <title>Essenya</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Navbar />
        <main className="pt-20">
          <PublicEventsCalendar />
          <Footer />
        </main>
      </>
    </>
  );
}
